# Generated by Django 5.0.2 on 2024-02-25 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ICAO_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('IATA_code', models.CharField(blank=True, max_length=3, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('STD', models.DateTimeField()),
                ('ATD', models.DateTimeField(null=True)),
                ('STA', models.DateTimeField()),
                ('ATA', models.DateTimeField(null=True)),
                ('airliner', models.CharField(max_length=20)),
                ('fromCity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departing_city', to='webPage.location')),
                ('toCity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrival_city', to='webPage.location')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userFlight', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='webPage.flight')),
            ],
        ),
    ]
