# Generated by Django 5.0.2 on 2024-02-26 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userFlight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='webPage.flight'),
        ),
    ]
